apiVersion: v1
kind: Pod
metadata:
  name: maria-db
  labels:
    app: maria-db
  annotations:
    description: "Banco de dados do projeto lanchonetebairro"
spec:
  containers:
    - name: maria-db
      image: mariadb:latest
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap